name: Build and Upload GLEW

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      # Checkout do código
      - name: Checkout repository
        uses: actions/checkout@v4

      # Configurar Python (necessário para o Conan)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Instalar o Conan
      - name: Install Conan
        run: |
          pip install conan
          conan --version

      # Configurar perfil do Conan
      - name: Configure Conan profile
        run: |
          conan profile detect
          conan profile show -pr default
        shell: pwsh

      - name: Install dependencies
        run: |
          conan install . --build=missing -s build_type=Release -o glew/*:shared=True
        shell: pwsh

      - name: Check GLEW DLL architecture with dumpbin
        run: |
          "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.*\bin\Hostx64\x64\dumpbin.exe" /headers $env:USERPROFILE\.conan2\p\**\bin\glew32.dll | findstr /C:"machine"
        shell: cmd

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: glew-libs
          path: |
            ~\.conan2\p\**\lib\*.lib
            ~\.conan2\p\**\bin\*.dll