name: Build with Conan and CMake

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Conan
        run: |
          python -m pip install --upgrade pip
          pip install conan
      - name: Create default Conan profile
        run: conan profile detect --force
      
      - name: Install dependencies with Conan
        run: |
          conan install . --build=missing `
            --settings os=Windows `
            --settings compiler=msvc `
            --settings compiler.version=192 `
            --settings compiler.runtime=dynamic `
            --settings build_type=Release `
            --settings arch=x86_64 `
            --generator CMakeDeps `
            --generator CMakeToolchain
      - name: Configure project with CMake
        run: |
          cmake . -G "Visual Studio 16 2019" -A x64 -DCMAKE_TOOLCHAIN_FILE=generators/conan_toolchain.cmake
          cmake --build . --config Release
      - name: Upload static libs
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build/