name: Build and Upload GLEW

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      # Checkout do código
      - name: Checkout repository
        uses: actions/checkout@v4

      # Configurar Python (necessário para o Conan)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Instalar o Conan
      - name: Install Conan
        run: |
          pip install conan
          conan --version

      # Configurar perfil do Conan
      - name: Configure Conan profile
        run: |
          conan profile detect
          conan profile update settings.compiler.version=193 conan/default
          conan profile update settings.compiler.runtime=dynamic conan/default

      # Instalar dependências com Conan
      - name: Install dependencies
        run: |
          conan install . --build=missing -s build_type=Release

      # Configurar CMake
      - name: Configure CMake
        run: |
          cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release

      # Compilar o projeto
      - name: Build
        run: |
          cmake --build build --config Release

      # Fazer upload das bibliotecas e DLLs como artefatos
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: glew-libs
          path: |
            build/**/glew*.lib
            build/**/glew*.dll