name: Build Windows Libraries

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
           
    - name: Install Conan
      run: |
          python -m pip install --upgrade pip
          pip install conan
      
    - name: Configure Conan for Windows
      run: |
        conan profile new default --detect --force
        conan profile update settings.compiler="msvc" default
        conan profile update settings.compiler.version=16 default
        conan profile update settings.compiler.runtime=MD default
        conan profile update settings.arch=x86_64 default
        conan profile update settings.build_type=Release default
        
    - name: Build libraries
      run: |
        # Atualizar ferramentas do Conan
        conan config install https://github.com/conan-io/conanclientcert.git
        conan remote add conancenter https://center.conan.io
        
        # Instalar e compilar bibliotecas
        conan install zlib/1.2.12@ --build=missing -s build_type=Release
        conan install boost/1.81.0@ --build=missing -s build_type=Release
        
        # Outras bibliotecas podem ser adicionadas aqui
        # conan install openssl/1.1.1t@ --build=missing
        
    - name: Package artifacts
      run: |
        mkdir artifacts
        robocopy "%USERPROFILE%\.conan\data" artifacts /E /NFL /NDL /NJH /NJS /nc /ns /np
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: windows-libraries
        path: artifacts
        retention-days: 5