name: Build GLEW with Conan

on:
  workflow_dispatch:  # Gatilho manual

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout do código
      - name: Checkout repository
        uses: actions/checkout@v2

      # Instalar o Conan
      - name: Install Conan
        run: |
          python -m pip install --upgrade pip
          pip install conan

      # Configurar o Visual Studio 2019 (v142)
      - name: Setup Visual Studio 2019 (v142)
        uses: microsoft/setup-msbuild@v1.1.0
        with:
          vs-version: 16.0 # VS 2019

      # Rodar o comando Conan para instalar dependências e compilar GLEW
      - name: Install dependencies with Conan
        run: |
          conan install . --build=missing `
            -s compiler="Visual Studio" `
            -s compiler.version=16 `
            -s compiler.runtime=MD `
            -s build_type=Release `
            -s arch=x86_64

      # Gerar as bibliotecas com MSBuild
      - name: Build with MSBuild
        run: |
          msbuild build\GLEW.sln /p:Configuration=Release /p:Platform=x64

      # Upload dos binários gerados
      - name: Upload static libs
        uses: actions/upload-artifact@v4
        with:
          name: glew-libs-and-headers  # Nome do artefato
          path: |
            build/bin/*       # Caminho para as DLLs
            build/lib/*       # Caminho para as LIBs estáticas
            build/include/*   # Caminho para os headers
